### ISSUE TITLE
[Feature Request] Ability to sort releases

### ISSUE THREAD

**Issue by JagandeepBrar** [LunaSeaApp/LunaSea#110]
**Describe the solution you'd like**
When manually searching for releases, offer the ability to sort the results by name, size, age, etc.

**Additional context**
https://www.reddit.com/r/LunaSeaApp/comments/ex3jzn/my_two_cents_of_feedback/

**Comment by jeff15110168** [comment]
This would be fantastic. Also filtering indexers (i.e. only show rarbg releases in manual search) would be an awesome power user feature!

**Comment by JagandeepBrar** [comment]
Moved to: https://feedback.lunasea.app/17
