### ISSUE TITLE
[Feature Request] Mylar support

### ISSUE THREAD

**Issue by DSN1138** [LunaSeaApp/LunaSea#121]
would it be possible to support Mylar for comic collections?

**Comment by JagandeepBrar** [comment]
This will be considered for the future!

Right now I want to get most of the video media-oriented software implemented, and then start to implement other software (like Mylar, Bazarr, LazyLibrarian, etc).

**Comment by JagandeepBrar** [comment]
Moved to: https://feedback.lunasea.app/9
