### ISSUE TITLE
[Feature Request] Ombi support

### ISSUE THREAD

**Issue by fletchto99** [LunaSeaApp/LunaSea#130]
**Describe the solution you'd like**

I'd love to see support for [Ombi](https://ombi.io/) from an administrator point of view (that is be able to approve request and see requests). Thanks for all of you hard work on the app so far!

**Comment by JagandeepBrar** [comment]
This is definitely planned in the future! Currently working on other things so going to label this as `not being worked on (for now)`.

**Comment by JagandeepBrar** [comment]
Moved to: https://feedback.lunasea.app/12
