### ISSUE TITLE
[Feature Request] Open links in a different browser

### ISSUE THREAD

**Issue by JagandeepBrar** [LunaSeaApp/LunaSea#138]
**Describe the solution you'd like**
When opening a link (web GUI, website, etc.), give the ability to open the link in another browser.

**Additional context**
This might be impossible, as there is no way to assign a "default" browser to `url_launcher`. Can take a look into seeing if Firefox, Chrome, etc. offer support for name links (ie `chrome://` and `Firefox://`).

https://www.reddit.com/r/LunaSeaApp/comments/f0qoc5/feature_request_option_to_choose_a_default/

**Comment by Elehiggle** [comment]
It is definitely possible. Apollo offers this option: 
![efef](https://user-images.githubusercontent.com/20746115/74092482-ceb16880-4ac4-11ea-8565-54171da816a0.PNG)

**Comment by JagandeepBrar** [comment]
@Elehiggle Apollo is also built using Swift not Flutter. As I said I’ll be trying the app link style URLs but there’s no guarantee that will work, if it doesn’t it might not be possible within Flutter at the moment. 

I’ll update the issue soon!

**Comment by JagandeepBrar** [comment]
This is being built and pushed right now in TestFlight build v2.1.0 (22)!
