### ISSUE TITLE
[Feature Request] Scale down text in NZBGet

### ISSUE THREAD

**Issue by Silent-Remux** [LunaSeaApp/LunaSea#140]
**Describe the solution you'd like**

NZBClient for iOS does a good job of showing lots of info in a small space. I'd like to see LunaSea make better use of the same area. The text size is too large and the bold just makes it harder to read. I'd like to be able to see the whole release name.

See photos.

![4D167DEF-1D92-4A83-A0C1-C816B46B1522](https://user-images.githubusercontent.com/16107603/74092509-eedd2980-4abc-11ea-8e72-3e8a06d4e0da.png)
![ED9C22F7-CB44-4036-B4B0-9648D57E853C](https://user-images.githubusercontent.com/16107603/74092510-f0a6ed00-4abc-11ea-8650-1ecc3e75fe33.png)

**Comment by simonk83** [comment]
Yep I agree with this. I was going to suggest some sort of auto scrolling for the name, or the ability to turn the phone on it’s side to see the full width of the title, but it makes more sense to just scale it down and display over multiple lines

**Comment by JagandeepBrar** [comment]
I agree with you both, I need to cleanup the way titles in a ListTile are represented when the text is very long. I will explore either an autoscrolling option or shrinking the text soon.

**Comment by simonk83** [comment]
I do think shrinking is probably the way to go. Auto scrolling is fine but I always find it a bit annoying as you have to sit and watch it until it gets to the part of the file name you need 😄

**Comment by JagandeepBrar** [comment]
Moving this request: https://feedback.lunasea.app/26
