### ISSUE TITLE
[Feature Request] Navigate to movie from Radarr History page

### ISSUE THREAD

**Issue by simonk83** [LunaSeaApp/LunaSea#154]
It’s the only page that doesn’t do it currently

**Comment by JagandeepBrar** [comment]
I purposely left it out because sometimes history items remain when a movie is deleted from Radarr. I'll take a look into a way to detect if it's been deleted and show a toast or something.

**Comment by JagandeepBrar** [comment]
This will be live in TestFlight v2.0.0 (77) in the next few hours!

Currently it's active in Lidarr and Radarr, Sonarr is the next service I am reimplementing and will be added and live probably by the end of this week.
