### ISSUE TITLE
[Feature Request] Add movies and shows to Radarr and Sonarr from search 

### ISSUE THREAD

**Issue by staticn0de** [LunaSeaApp/LunaSea#170]
**Describe the solution you'd like**
It would be good if it were possible to say long press on a movie found in search and have a “add to Radarr” button which brings up a Radarr add movie search and also sends the movie to the downloaded so it’s post processed when it’s done.

**Comment by JagandeepBrar** [comment]
Just to confirm I understand, you mean from Indexer search correct?

I can take a look into a way to connect the two, the search results only return basic metadata information that would make it difficult to directly push it from the search to Radarr/Sonarr with the correct movie/show selected, but I'll investigate!

**Comment by staticn0de** [comment]
Yep, I mean indexer search. If I recall right (it’s been a while since I was on Android) NZB360 had a similar feature that let you add and search a movie. When you searched using index search, you could add the movie to Radarr and then it would send the same one you searched to be downloaded so it was managed with Radarr.

**Comment by JagandeepBrar** [comment]
Moved: https://feedback.lunasea.app/30
