### ISSUE TITLE
[Bug] NZBHydra Categories Not Loading

### ISSUE THREAD

**Issue by benjmd** [LunaSeaApp/LunaSea#172]
Hiya, appears NZBHydra2 (v2.14.2 via docker) categories stopped working since the last testflight release (currently on v2.0.0 (55)). No issues with other newznab sites (tested with nzb.su/nzbfinder/nzbgeek). I've removed/readded, no change. Open to suggestions :)

**Comment by JagandeepBrar** [comment]
Hey there thanks for pinpointing the issue!

I seem to be running into the same issue, looks to happen when I set the user-agent which is needed for some indexers. I will look into a way to remedy this and it should be in a TestFlight update in the coming days!

**Comment by JagandeepBrar** [comment]
As an update, I was able to find the issue, it has been fixed in an internal build and will be live in TestFlight soon!

**Comment by JagandeepBrar** [comment]
This has now been fixed with v2.0.0 (66) which is now on TestFlight!
