### ISSUE TITLE
[Feature Request] Accept RAR as a valid filetype for SABnzbd

### ISSUE THREAD

**Issue by peskdale** [LunaSeaApp/LunaSea#181]
**Describe the solution you'd like**
Permit RAR files to be uploaded to SABnzbd.

**Additional context**
Per the wiki, RAR (and GZIP) is an accepted file format for SABnzb, and can be uploaded via the web GUI. It would be helpful if LunaSea could mirror this compatibility.
https://sabnzbd.org/wiki/introduction/usage

**Comment by JagandeepBrar** [comment]
This should be easy enough to add, didn't realize RARs were accepted formats (since most indexers multi-download is zip format).

I just submitted v2.0.0 to Apple, so I can add this in a v2.x release!

**Comment by JagandeepBrar** [comment]
This has now been implemented in the `v2.1.0` branch.

https://github.com/LunaSeaApp/LunaSea/commit/85466439fcf234a96a9be84a960374a297fbdc32

Will be live in the next TestFlight (this week)!
