### ISSUE TITLE
[Feature Request] Sonarr v3

### ISSUE THREAD

**Issue by abb0r** [LunaSeaApp/LunaSea#184]
In Sonarr v3 you now have 2 different profiles when adding a show: quality and language. It would be nice if the language profile selection would be added to Lunasea.

**Comment by JagandeepBrar** [comment]
Sonarr v3 support is definitely planned, stay tuned. Going to change the title of  the issue to just "Sonarr v3" because I will support all v3 features in one release.

**Comment by d2dyno** [comment]
Definitely appreciate this! Searching a new show to add doesn’t work with Sonarr v3 and current app version

**Comment by JagandeepBrar** [comment]
@d2dyno I believe it should still work in its current state with v3, other users have reported it still works but not the new functionality.

**Comment by theg00s3** [comment]
> Searching a new show to add doesn’t work with Sonarr v3 and current app version
@d2dyno that definitely works with the current versions of LunaSea and Sonarr V3

**Comment by JagandeepBrar** [comment]
I am moving the issue to here: https://feedback.lunasea.app/6
