### ISSUE TITLE
[Bug] Typo when adding a movie

### ISSUE THREAD

**Issue by abb0r** [LunaSeaApp/LunaSea#185]
When adding a movie with Radarr, there is a small typo. The last button should say "Availability".
![20-04-02 04-23-35 9342](https://user-images.githubusercontent.com/8042012/78205509-90b93b00-749c-11ea-9848-36199c883bf8.png)

**Comment by JagandeepBrar** [comment]
Thanks for finding the bug! I have fixed the bug with a commit on `v2.1.0` branch here:

https://github.com/LunaSeaApp/LunaSea/commit/dcebf8ff116042da80a071fce2d69040e2bb86de

Will be included in the next TestFlight, will update here when it is live!
