### ISSUE TITLE
Localhost connections

### ISSUE THREAD

**Issue by NDuggan** [LunaSeaApp/LunaSea#190]
**Describe the Bug**
My services are not exposed to the outside world, but are all available on my local network. Meaning I can VPN to my home network and access everything that way.

I've been able to setup NZBGet within LunaSea using for example: http://192.168.0.10:6789. The test connection works fine and I can then access NZBGet via the app.

When I try to do the same for Radarr and Sonarr (http://192.168.0.10:7878/8989), the test connection fails. If I save the config and enable it (with it failing) and then click "open web GUI" and it will successfully load in the built in browser, but I can't fetch any information via the actual app.

**To Reproduce**
Add config for a Radarr/Sonarr service which is only available on your current network.

**Expected Behaviour**
It should connect like NZBGet does.

**Screenshots**
N/A

**Versions**
LunaSea: 2.0.0 (333)
NZBGet: v21.0
Radarr: 2.0.1480
Sonarr: 3.0.3.737

**Additional context**
N/A

**Comment by NDuggan** [comment]
FFS ignore me. I completely glossed over the API key, as I thought it said authorisation. It’s been a long week 🤣 great work on the app though!

**Comment by JagandeepBrar** [comment]
Glad you got it solved and thanks for the kind words! :)
