### ISSUE TITLE
[Feature Request] Support for Netdata

### ISSUE THREAD

**Issue by cwilcoxc** [LunaSeaApp/LunaSea#191]
**Describe the solution you'd like**
Support for netdata

**Additional context**
https://github.com/netdata/netdata

**Comment by JagandeepBrar** [comment]
Hey there!

Netdata support is in the pipeline! I have a good list of 30+ services users (and myself) want to see support for in LunaSea, so I can't offer any timeline right now. Next up for a new software though is going to be Tautulli.

**Comment by JagandeepBrar** [comment]
Moved to: https://feedback.lunasea.app/16
