### ISSUE TITLE
[Bug] Season monitoring toast is incorrect

### ISSUE THREAD

**Issue by julian-str** [LunaSeaApp/LunaSea#193]
Hi again.
When I change the monitoring status of a season in sonarr the notification shows the status of the tv show instead.

If the show is monitored and i unmonitor a season the notification still says ‚monitoring season‘. Remonitoring the season also shows ‚monitoring season‘.
If the show is unmonitored the notification shows ‚no longer monitoring‘ for both, monitoring and unmonitoring a season.

The notification text for episodes and tv shows seem to work correctly.

Just something for the backlog :)

**Comment by JagandeepBrar** [comment]
Thanks for notifying me on this!

Simple fix that I have already done internally, but I submitted v2.0.1 to Apple before this fix was implemented so it will be in the first TestFlight of v2.1.0!

**Comment by julian-str** [comment]
Perfect 😊👍🏻

**Comment by JagandeepBrar** [comment]
Fixed in https://github.com/LunaSeaApp/LunaSea/tree/dfa3eb167ed45b2c18c6a79dc42912353a1cac1e.

Will be live in TestFlight v2.1.0 (11).
