### ISSUE TITLE
[Feature Request] 

### ISSUE THREAD

**Issue by mlavio829** [LunaSeaApp/LunaSea#196]
An awesome feature would be to have the ability to perform a manual search for shows in Sonarr. You can do this with Radarr by performing a manual search however this does not appear to be an option in Sonarr via LunaSea.

**Comment by JagandeepBrar** [comment]
This is already implemented for both.

For Radarr, there's a large "manual" button on the search page for a movie.

For Sonarr, you just need to long-press the search icon on the right side of the episode tile to trigger a manual search.

**Comment by mlavio829** [comment]
Perfect! Thank you- I didn't realize you had to long press for Sonarr. That works!
