### ISSUE TITLE
[Feature Request] Server Statistics from SabNZBd

### ISSUE THREAD

**Issue by julian-str** [LunaSeaApp/LunaSea#199]
**Describe the solution you'd like**
SabNZBd offers statistics for usage of configured servers.
Lunasea has already some basic statistics but if possible I would like to see more information there.

**Additional context**
Found in settings->servers of SabNZBd:

![image](https://user-images.githubusercontent.com/29665092/79744552-d5e7c480-8306-11ea-8c9b-3eb79234d7a8.jpeg)

**Comment by JagandeepBrar** [comment]
Specifically what more would you like to be shown?

In Server Statistics view currently can see:
- Uptime
- SABnzbd version
- Free space on hard drive
- Speed limit
- Statistics for daily/weekly/monthly/total usage

It should be relatively simple to add more, let me know what you would like from what is available via the `fullstatus` call to SABnzbd's API: https://sabnzbd.org/wiki/advanced/api#fullstatus

**Comment by julian-str** [comment]
Ah good to see that this is accessible in the api.

I would like to see the stats day, week, month, total for each server and the combined for those stats thats already in app.
Also you have the possbility to reset server stats in sab to accurately measure usenet block usage.
Do you know if thats also accessible via the api?

**Comment by JagandeepBrar** [comment]
The API isn't too clear on if that is possible but I can update you on that soon.

Adding the server-specific stats is relatively simple, I can get it in for the next release. v2.1.0 (current TestFlight) is pushing out it's last release now, which is what will go live in the App Store without this update though.

**Comment by JagandeepBrar** [comment]
Moved: https://feedback.lunasea.app/29
