### ISSUE TITLE
[Feature Request] Back Button Opens Drawer

### ISSUE THREAD

**Issue by royaltongue** [LunaSeaApp/LunaSea#212]
Can an option be added to allow opening the drawer by pressing the back button when at the "top" of a section?

Currently it just closes the application

**Comment by JagandeepBrar** [comment]
This has already been requested and will be implemented in the next release. Closing this issue in favour of the first one created, #211.

**Comment by JagandeepBrar** [comment]
https://github.com/LunaSeaApp/LunaSea/issues/211#issuecomment-631747342

Just to let you know this has been implemented and detailed above! Will be live in the next beta release this week.
