### ISSUE TITLE
[Feature Request] Bazarr Support for Subtitles

### ISSUE THREAD

**Issue by CraftyCanine** [LunaSeaApp/LunaSea#42]
First off, this is an amazing app! It already looks amazing. I can't wait to see where it goes from here. Please consider adding support for Bazarr, a fork of Radarr/Sonarr that does subtitle management for both movies and TV.

https://www.bazarr.media/

**Comment by JagandeepBrar** [comment]
Thanks for the request and nice words!

I took around Bazarr's repository and can't seem to find any documentation for an API. I'll contact the developer to see if there is an API... Without one, I'm sorry, but I won't be able to integrate Bazarr into LunaSea :(

**Comment by JagandeepBrar** [comment]
https://github.com/morpheus65535/bazarr/issues/741

Here is the issue I made on the bazarr repository asking about an API!

**Comment by CraftyCanine** [comment]
Followed that one as well. Thanks!

**Comment by JagandeepBrar** [comment]
https://github.com/morpheus65535/bazarr/issues/741#issuecomment-571379087

He mentions that they are working on a new REST API, so I will wait for that to be implemented before implementing Bazarr since the 4 API calls that are available are very limited as well as not having any authentication.

**Comment by JagandeepBrar** [comment]
Moved to: https://feedback.lunasea.app/11

**Comment by gerwim** [comment]
Any updates on this (link above is dead)? The API is implemented (as seen https://github.com/morpheus65535/bazarr/blob/master/bazarr/api.py).

**Comment by bonswouar** [comment]
@gerwim Here is the working link: https://feedback.lunasea.app/b/feedback/p/bazarr-support
