### ISSUE TITLE
[Feature request] Dark mode

### ISSUE THREAD

**Issue by Lasikie** [LunaSeaApp/LunaSea#58]
Any chance of adding a pure black mode?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by JagandeepBrar** [comment]
Could be considered in the longterm future, but not high on the list. Going to focus on feature implementations before smaller QoL changes like this.

**Comment by JagandeepBrar** [comment]
This has been added into the most recent TestFlight release! You can enable it in Settings -> Modules -> LunaSea.
