### ISSUE TITLE
[Feature Request] Customisable Summary view

### ISSUE THREAD

**Issue by simonk83** [LunaSeaApp/LunaSea#71]
At the moment it shows the number of shows/movies available, which is cool but not something I particularly care about. It’d be nice to be able to choose from a few stats to display though. 
For example, upcoming shows/movies in the next week would be good to see at a glance (and then the ability to click that and be taken to a list of them)

**Comment by JagandeepBrar** [comment]
This is planned in the future, the Home page is definitely very sparse and needs more things to be added.

Specifically I think it will be useful for when monitoring services are integrated (like being able to see how many streams are active right now, CPU usage, etc.).

I can take a look into adding some sort of "upcoming" section that creates a merged calendar with the 3 --rr services.

**Comment by simonk83** [comment]
> I can take a look into adding some sort of "upcoming" section that creates a merged calendar with the 3 --rr services.

Yep that would be really great, and I'd probably use that feature more than anything else (though that may just be me).  [Organizr](https://github.com/causefx/Organizr), which is like a web dashboard for this stuff, does the same thing and it's super useful:

eg; 

![image](https://user-images.githubusercontent.com/518440/73218931-12e06700-41af-11ea-8a1c-5db737463678.png)

**Comment by JagandeepBrar** [comment]
Shifting feature requests away from GitHub, you can follow this request here: https://feedback.lunasea.app/25
