### ISSUE TITLE
[Feature Request] see profiles in side drawer

### ISSUE THREAD

**Issue by alanshelley** [LunaSeaApp/LunaSea#85]
Just an idea for a modification to the side drawer: 

Instead of dividing it up by automation and clients, divide it up by profile. As it is now, when entering different sections of the app, each drop down section collapses and then requires multiple taps to get around. 

If it was divided up by profile, it could always be open and easily accessed. 

Home
Settings
—————————
Profile 1
-radarr
-sonarr
-etc 

Profile 2
-radarr 
-sonarr
-etc

Something along those lines maybe?

**Comment by JagandeepBrar** [comment]
I'm going to take a look into the best way to present the profiles. Currently I am going to focus on easing the profile switching experience before looking at a UI rework!

**Comment by alanshelley** [comment]
Yeah that definitely makes sense. Looking forward to what you come up with.

**Comment by JagandeepBrar** [comment]
I forgot to close this issue, but changing profiles via the drawer has been live in the TestFlight releases for a while and will come to production in v2.0.0!
