### ISSUE TITLE
[Feature Request] Google oAuth support

### ISSUE THREAD

**Issue by HariboApfel** [LunaSeaApp/LunaSea#86]
i have sonarr and radarr setup behind google oauth. mba make it possible to get the oauth cookies via an inapp browser?

**Comment by JagandeepBrar** [comment]
Could you send me a link to a tutorial you may have followed to set this up?

Easiest way for me to implement it would be to use the same setup and get it connected.

**Comment by robflate** [comment]
Here's a tutorial;

https://www.smarthomebeginner.com/traefik-2-docker-tutorial/

**Comment by JagandeepBrar** [comment]
@robflate thanks for the link!

I am moving the issue here: https://feedback.lunasea.app/18

**Comment by timmehtimtims** [comment]
Any update on progress on this?
