### ISSUE TITLE
[Feature Request] Support for torrent clients

### ISSUE THREAD

**Issue by JagandeepBrar** [LunaSeaApp/LunaSea#90]
You guys can request any torrent clients you guys use here, and when I start implementing the clients I will know where to start!

**Comment by JagandeepBrar** [comment]
qBittorrent (#49).

**Comment by JagandeepBrar** [comment]
Deluge (#55).

**Comment by Silent-Remux** [comment]
rtorrent please

**Comment by simonk83** [comment]
Transmission please

**Comment by Nach0-Stallion** [comment]
Another vote for transmission please. ❤️

**Comment by ptiagosequeira** [comment]
One vote to qBittorrent

**Comment by JagandeepBrar** [comment]
> One vote to qBittorrent. Do you plan to support torrent search through Jackett?

@ptiagosequeira Not sure at the moment, won't make any promises but hopefully yes! I want to support as much as I can.

**Comment by b055k4133** [comment]
uTorrent please x

**Comment by JagandeepBrar** [comment]
I am moving feature requests to a different location, you can follow torrent support here: https://feedback.lunasea.app/23

**Comment by kifujin** [comment]
Moved to [here](https://feedback.lunasea.app/b/feedback/p/torrent-clients-support), I think?

**Comment by onedr0p** [comment]
Not sure where is live now, but it's in the docs

https://docs.lunasea.app/getting-started/frequently-asked-questions#torrent-client-support-is-it-coming

**Comment by mritunjaymusale** [comment]
Based on what's written on the docs and Apple being a dick, we might have to wait till end of 2024 when the new EU Law will force apple to allow 3rd party app stores on all their products. 
Then this app can be distributed through FDroid equivalent of iOS

**Comment by Nanorithm** [comment]
Would it be possible to provide an IPA file for sideloaders with this feature enabled? I think that's probably the simplest 'workaround' at the moment. I'd be happy to draw up a guide on sideloading as well if you'd want to add it to the docs.

**Comment by ssbarnea** [comment]
the two links to external feature request are no longer available. If you want to keep the issue tracker clean, you could use github discussions instead.. and best part is that you can just convert an issue into a discussion!

there are other apps in appstore that manage torrents, the only trick is to not name/advertise it as a torrenting app. "remote management" is a common phrase used. also now we have alternative stores enabled so no real reasons for not adding this feature. maybe reopen?
