### ISSUE TITLE
[Feature Request] LazyLibrarian support

### ISSUE THREAD

**Issue by rodalpho** [LunaSeaApp/LunaSea#91]
I would like to see the LazyLibrarian eBook download client supported similarly to Radarr and Sonarr. It's much less mature and pretty klunky, but it does work!

https://gitlab.com/LazyLibrarian/LazyLibrarian

**Comment by JagandeepBrar** [comment]
This will be considered for the future!

Right now I want to get most of the video media-oriented software implemented, and then start to implement other software (like Mylar, Bazarr, LazyLibrarian, etc).

**Comment by JagandeepBrar** [comment]
Moved to: https://feedback.lunasea.app/14
